baseURL = 'https://www.larrycancode.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'custom'
publishDir = 'docs'


[menu]
[[menu.main]]
name = "about"
URL = "/"
weight = 1

[[menu.main]]
name = "projects"
URL = "/projects"
weight = 2

[[menu.main]]
name = "blog"
URL = "/posts"
weight = 3

[[menu.main]]
name = "contact"
url = "/contact" #this is the link I want to add
weight = 4